format:
  html:
    theme:
      - cosmo
      - vp.scss
  pdf:
    documentclass: scrreprt
    code-link: true


project:
  type: book

book:
  title: "Einführung in die Vergleichende Politikwissenschaft"
  reader-mode: true
  page-footer:
    left: |
      Lehrbuch für die Universität Bremen und die JGU Mainz.
    right: |
      Geschrieben mit <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  author: "Philip Manow und Armin Schäfer"
  date: today
  date-format: DD.MM.YYYY
  
  chapters:
    - index.qmd
    - Einleitung.qmd
    - Staat.qmd
    - Demokratisierung.qmd
    - Demokratie-oder-Diktatur.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib


